<a href="https://colab.research.google.com/github/kleysonr/google-colab/blob/deeplearning/Label_encoders.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# Classes to be encoded in numeric arrays
classes = ['yes','yes','no','no','maybe','no','yes']

In [7]:
from sklearn.preprocessing import LabelEncoder

# LabelEncoder will generate an array where the class name is replaced by a given number that represent uniquely a given class.
le = LabelEncoder()
labels = le.fit_transform(classes)

print('Y labels: ', classes)
print('Encoded labels: ', labels)
print('Classes names', le.classes_)

Y labels:  ['yes', 'yes', 'no', 'no', 'maybe', 'no', 'yes']
Encoded labels:  [2 2 1 1 0 1 2]
Classes names ['maybe' 'no' 'yes']


In [8]:
from sklearn.preprocessing import LabelBinarizer

# LabelBinarizer will generate an One-hot enconding matrix.
# One hot encoding transforms categorical features to a format that works with some classification and regression algorithms.
# The algorithm will generate one boolean column for each category. Only one of these columns could take on the value 1 for each sample, representing the class.
# Hence, the term one hot encoding.

lb = LabelBinarizer()
labels = lb.fit_transform(classes)

print('Y labels: ', classes)
print('Encoded labels: ', labels)
print('Classes names', lb.classes_)

Y labels:  ['yes', 'yes', 'no', 'no', 'maybe', 'no', 'yes']
Encoded labels:  [[0 0 1]
 [0 0 1]
 [0 1 0]
 [0 1 0]
 [1 0 0]
 [0 1 0]
 [0 0 1]]
Classes names ['maybe' 'no' 'yes']


In [9]:
from sklearn.preprocessing import LabelEncoder
from keras.utils import np_utils
import numpy as np

# One hot encoding using Keras

_classes = np.array(classes)
size = np.unique(_classes).size

le = LabelEncoder().fit(classes)
labels = np_utils.to_categorical(le.transform(classes), size)

print('Y labels: ', classes)
print('Encoded labels: ', labels)
print('Classes names', le.classes_)

Using TensorFlow backend.


Y labels:  ['yes', 'yes', 'no', 'no', 'maybe', 'no', 'yes']
Encoded labels:  [[0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Classes names ['maybe' 'no' 'yes']
